### ISSUE TITLE
自助という観点での調査

### ISSUE THREAD

**Issue by tsu-nera** [peach-hack/titan#4]
* リワーク体験  ... リワークで仲間とうつの体験を共有することで、回復に向かった
* みんチャレ体験 ... チームを組んで励まし合うことで、目標達成
* 3ヶ月プログラム ... チームを組んで励まし合うことで、目標達成
* SA-Program ... アノニマスのひとたちが悩みを共有する会合に何度も出席。

**Comment by tokidrill** [comment]
これなら私も経験があります。
* 共同生活…エンジニア未経験時代、会社に行きたくないという悩みを抱えた友人の家に転がり込み私はプログラミングの学習、友人は会社に行くもしくは転職するための勉強(コピーライターになりたいそうな)をしました。具体的な成果の報告でなくて、今日はどんな気持ちだったか、とかここは反省している、とか後は一緒に酒を飲んでストレスを発散したり、お互いの苦手分野をカバーしあったりというところです。
